name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Explain what you were doing, what you expected to happen, and what actually happened. The more details you provide, the better we can help you!
      placeholder: Describe the bug here
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      description: What Apple device did you run into this bug on?
      placeholder: Apple Device
    validations:
      required: true

